backend:
    name: github
    repo: gerbilsinspace/abell-design
media_folder: static/assets
public_folder: assets
media_folder_relative: true
collections:
    - name: pages
      label: Pages
      files:
          - label: 'Home'
            name: 'home'
            file: 'content/pages/home.md'
            fields:
                - name: title
                  label: Title
                  widget: string
                  default: Home
                - name: images
                  label: 'Images'
                  widget: list
                  fields:
                      - name: image
                        label: Image
                        widget: image
                        media_library:
                            config:
                            multiple: true
